name: build_and_test

on: [push, pull_request]

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        build_type: [Release, Debug]
        option: [default, ref, shared, no_sample, no_data, fbx, no_gltf]

    steps:
    - uses: actions/checkout@v2
    
    - name: install mesa dependency
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get install libgl1-mesa-dev libglu1-mesa-dev
    
    - name: Install linux fbx sdk
      if: matrix.option == 'fbx' && matrix.os == 'ubuntu-latest'
      run: |
        mkdir fbx
        cd fbx
        sudo wget 'https://www.autodesk.com/content/dam/autodesk/www/adn/fbx/2020-2/fbx20202_fbxsdk_linux.tar.gz' -O 'fbx.tar.gz'
        sudo tar -xf 'fbx.tar.gz'
        (yes yes | sudo ./*_fbxsdk_linux /usr/local) || true
        sudo chmod -R 755 /usr/local/lib
        sudo chmod -R 755 /usr/local/include
        cd ..
    
    - name: Install windows fbx sdk
      if: matrix.option == 'fbx' && matrix.os == 'windows-latest'
      run: |
        md fbx
        cd fbx
        Start-BitsTransfer -Source 'https://www.autodesk.com/content/dam/autodesk/www/adn/fbx/2020-2/fbx20202_fbxsdk_vs2019_win.exe' -Destination 'fbxsdk.exe'
        Start-Process -FilePath 'fbxsdk.exe' /S -Wait
        cd ..
        
    - name: Install macos fbx sdk
      if: matrix.option == 'fbx' && matrix.os == 'macos-latest'
      run: |
        mkdir fbx
        cd fbx
        sudo wget 'https://www.autodesk.com/content/dam/autodesk/www/adn/fbx/2020-2/fbx20202_fbxsdk_clang_mac.pkg.tgz' -O 'fbx.tgz'
        sudo tar -xf 'fbx.tgz'
        sudo installer -pkg *_fbxsdk_clang_macos.pkg -target /
        cd ..
    
    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory.
      run: |
        cmake --version
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DBUILD_SHARED_LIBS=${{matrix.option == 'shared'}} -Dozz_build_simd_ref=${{matrix.option == 'ref'}} -Dozz_build_samples=${{matrix.option != 'no_sample'}} -Dozz_build_data=${{matrix.option != 'no_data'}} -Dozz_build_gltf=${{matrix.option != 'no_gltf'}}
    
    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}} --use-stderr

    - name: Test
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.
      run: ctest -C ${{matrix.build_type}} --output-on-failure
      
