name: build_and_test

on: [push]

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        build_type: [Release, Debug]
        math: [simd,ref]
        include:
          - os: ubuntu-latest
            generator_option: '-j4'
          - os: macos-latest
            generator_option: '-j4'
            
    env:
      ozz_simd_ref: ${{ matrix.math == 'ref' }}

    steps:
    - uses: actions/checkout@v2
    - name: install mesa dependency
      run: |
        sudo apt-get install libgl1-mesa-dev libglu1-mesa-dev
      if: matrix.os == 'ubuntu-latest'

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory.
      run: |
        cmake --version
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -Dozz_build_simd_ref=${{env.ozz_simd_ref}}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}} --use-stderr -- ${{matrix.generator_option}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.
      run: ctest -C ${{matrix.build_type}} --output-on-failure -- ${{matrix.generator_option}}
      
